---
efiBootLoader: "systemd-boot"

kernelSearchPath: "/boot"
kernelPattern: "^vmlinuz.*"

loaderEntries:
  - "timeout 0"
  - "console-mode keep"
  - "editor no"

kernelParams: [ "quiet", "splash" ]

efiBootloaderId: "Arasaka"
installEFIFallback: true
