---
initialPartitioningChoice: erase
initialSwapChoice: none

userSwapChoices:
    - none

allowManualPartitioning: false

defaultPartitionTableType: gpt
defaultFileSystemType:  "ext4"

luksGeneration: luks2
drawNestedPartitions:   false
alwaysShowPartitionLabels: true

partitionLayout:
    - name: "EFI"
      type: "uefi"
      filesystem: "fat32"
      mountPoint: "/boot/efi"
      size: "1G"
    - name: "arasaka-boot"
      filesystem: "ext4"
      mountPoint: "/boot"
      size: "2G"
    - name: "arasaka-slot-a"
      filesystem: "ext4"
      mountPoint: "/"
      size: "20G"
    - name: "arasaka-slot-b"
      filesystem: "ext4"
      size: "20G"
    - name: "arasaka-data"
      filesystem: "btrfs"
      mountPoint: "/data"
      size: "100%"
