---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    5.5
    requiredRam:        1.0
    check:
        - storage
        - ram
        - power
        - root
        - screen
    required:
        - ram

geoip:
    style:    "none"
    url:      "https://geoip.kde.org/v1/ubiquity"
    selector: "CountryCode"
