#!/usr/bin/env bash
# arasaka-postinstall.sh
# Calamares post-install hook (shellprocess, dontChroot=true): records the
# active A/B slot on the freshly installed system, moves flatpak apps onto the
# shared btrfs data partition so they survive A/B updates, and finalizes the
# installed system (installer stripped, sudo/su/pkexec disabled, AppArmor
# guard armed) via scripts/arasaka-finalize-install.sh. The systemd-boot
# entries are left to the Calamares bootloader module (they reference the root
# by UUID); the A/B loader entries are generated by the running system's
# update machinery once the installed layout is known.
#
# $1 = ${ROOT} as expanded by Calamares (target root mount point).
set -euo pipefail

TARGET="${1:-}"
TARGET="${TARGET%/}"
if [ -z "$TARGET" ] || [ ! -d "$TARGET" ]; then
    echo "[arasaka-postinstall] ERROR: no valid target root: '${1}'" >&2
    exit 1
fi

echo "[arasaka-postinstall] Target root: ${TARGET}"

mkdir -p "${TARGET}/boot/ab"
echo "a" > "${TARGET}/boot/ab/active-slot"

# The root mount is handled by the arasaka-ab initramfs hook (by slot label);
# fstab must NOT reference a specific slot's root device or systemd would try
# to remount it over whatever slot is actually active. Strip the "/" entry.
if [ -f "${TARGET}/etc/fstab" ]; then
    grep -Ev '^[^#[:space:]][^[:space:]]+[[:space:]]+/[[:space:]]' \
        "${TARGET}/etc/fstab" > "${TARGET}/etc/fstab.arasaka"
    mv "${TARGET}/etc/fstab.arasaka" "${TARGET}/etc/fstab"
    echo "[arasaka-postinstall] Removed root mount entry from fstab"
fi

# Move the system-wide flatpak store onto the shared btrfs data partition and
# bind-mount it back. A/B slot updates do NOT copy /var/lib/flatpak (it is ~6G
# and the update engine rsyncs the running root to the inactive slot), so apps
# installed into the ISO would be lost on the first update otherwise. With the
# bind mount every slot sees the same store on /data.
if mountpoint -q "${TARGET}/data" || [ -d "${TARGET}/data" ]; then
    echo "[arasaka-postinstall] Moving flatpak store to data partition..."
    mkdir -p "${TARGET}/data/flatpak"
    if [ -d "${TARGET}/var/lib/flatpak" ] && [ -z "$(ls -A "${TARGET}/data/flatpak" 2>/dev/null)" ]; then
        cp -a "${TARGET}/var/lib/flatpak"/. "${TARGET}/data/flatpak/" 2>/dev/null || true
    fi

    # Replace the per-slot flatpak dir with a mountpoint for the bind mount.
    rm -rf "${TARGET}/var/lib/flatpak"
    mkdir -p "${TARGET}/var/lib/flatpak"

    # Bind mount in fstab. /data is already an fstab entry (btrfs, by UUID);
    # add a second entry that binds /data/flatpak onto /var/lib/flatpak. The
    # bind depends on /data being mounted, which systemd orders automatically.
    if ! grep -q " /var/lib/flatpak " "${TARGET}/etc/fstab"; then
        printf '%s\n' \
            "/data/flatpak  /var/lib/flatpak  none  bind  0 0" \
            >> "${TARGET}/etc/fstab"
        echo "[arasaka-postinstall] fstab bind: /data/flatpak -> /var/lib/flatpak"
    fi
else
    echo "[arasaka-postinstall] WARNING: no /data mount in target; flatpak store stays on the slot (will be lost on A/B update)"
fi

# Finalize the installed system: strip the installer, disable privilege
# escalation (no wheel/sudo members, no sudoers.d, locked root, no setuid
# pkexec/sudo/su), arm the AppArmor escalation guard and add tmpfs /var/tmp.
# Shared with build-bundle.sh so OTA bundles ship the same locked-down shape.
if [ -x "${TARGET}/usr/local/bin/arasaka-finalize-install.sh" ]; then
    echo "[arasaka-postinstall] Running finalize-install hardening..."
    "${TARGET}/usr/local/bin/arasaka-finalize-install.sh" "${TARGET}"
else
    echo "[arasaka-postinstall] WARNING: finalize-install script missing in target" >&2
fi

# COSMIC Initial Setup is a first-login wizard that looks like an installer and
# can hang if it can't reach its daemon. The autostart entry is what pops it on
# login, so removing it stops the wizard on the installed system.
rm -f "${TARGET}/etc/xdg/autostart/com.system76.CosmicInitialSetup.desktop" \
      "${TARGET}/usr/share/applications/com.system76.CosmicInitialSetup.desktop" \
      "${TARGET}/usr/share/polkit-1/rules.d/20-cosmic-initial-setup.rules" \
      2>/dev/null || true

mkdir -p "${TARGET}/etc/arasaka"
echo "a" > "${TARGET}/etc/arasaka/active-slot"

echo "[arasaka-postinstall] Active slot recorded as 'a'"

# The unpacked rootfs carries the archiso-built initramfs (with archiso
# hooks). Switch it to the busybox-style initramfs so the arasaka-ab hook can
# override the root mount handler (the systemd initramfs hook cannot run
# run_hook() mount_handler overrides), then regenerate it for a plain disk
# install so the installed system boots from the active A/B slot.
echo "[arasaka-postinstall] Forcing busybox initramfs (arasaka-ab hook + plymouth)..."
if [ -f "${TARGET}/etc/mkinitcpio.conf" ]; then
    sed -i -E 's/^HOOKS=\(.*\)$/HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck arasaka-ab)/' \
        "${TARGET}/etc/mkinitcpio.conf"
fi
echo "[arasaka-postinstall] Regenerating initramfs in target..."
if chroot "${TARGET}" /usr/bin/mkinitcpio -P; then
    echo "[arasaka-postinstall] initramfs regenerated"
else
    echo "[arasaka-postinstall] WARNING: mkinitcpio regeneration failed" >&2
fi
